#!/data/data/com.termux/files/usr/bin/python
import platform,os
os.system("git pull")
os.system("apt update && apt upgrade -y")
os.system("pkg update && pkg upgrade -y")
bit = platform.architecture()[0]
if bit == '64bit':
    import new_64
elif bit == '32bit':
    import new_32